### ISSUE TITLE
Question: instructions for building standalone binary?

### ISSUE THREAD

**Issue by gheinrich** [astefanutti/kubebox#28]
Hello, how would you recommend building a standalone `kubebox` binary out of source code? Assuming for example linux-x86.

Thanks!

**Comment by astefanutti** [comment]
There are multiple ways to build binaries for Linux.

To replicate the binary that gets published for each release, you can use [astefanutti/scratch-node](https://github.com/astefanutti/scratch-node) as the basis and replace the following pieces:

https://github.com/astefanutti/scratch-node/blob/6796615fb0a0d70c19991113fc27c04ba7a2424a/Dockerfile#L10-L41

with:

```dockerfile
RUN npm install
RUN npm run executable-linux
```

That should create a fully statically linked `kubebox` binary.

Otherwise you can just run `npm run executable` which should produce a binary dynamically linked with glibc.

Last but not least, in case you just want to have a binary that contains a7f624ba475783098568e9aef46c4ef0b6f9f7db, I'll try to cut a new release ASAP.

**Comment by gheinrich** [comment]
Thanks!
